name: Container test

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        testingTargetBaseName: [
          "mongodb",
          "postgresql"
        ]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-app-${{ matrix.testingTargetBaseName }}-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-app-${{ matrix.testingTargetBaseName }}-
          ${{ runner.os }}-buildx-app-
    - name: Build
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./docker/Dockerfile
        platforms: linux/amd64
        push: true
        build-args: |
          packageScope=@awesome-backup/${{ matrix.testingTargetBaseName }}
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,mode=max,dest=/tmp/.buildx-cache-new
        tags: ${{ matrix.testingTargetBaseName }}
    - name: Move cache
      run: |
        rm -rf /tmp/.buildx-cache
        mv /tmp/.buildx-cache-new /tmp/.buildx-cache
    - uses: brpaz/structure-tests-action@v1.1.2
      with:
        image: ${{ matrix.testingTargetBaseName }}
        configFile: ./docker/test/${{ matrix.testingTargetBaseName }}/structure-tests.yml
